// Generated by CoffeeScript 1.9.3
(function() {
  var config, config_extra, deepMerge, env, err, file_extra, fs;

  fs = require('fs-extra');

  deepMerge = function(target, source) {
    var sourceValue, sourcekey, targetValue;
    for (sourcekey in source) {
      sourceValue = source[sourcekey];
      targetValue = target[sourcekey];
      if (targetValue && sourceValue && typeof sourceValue === 'object') {
        deepMerge(targetValue, sourceValue);
      } else {
        target[sourcekey] = sourceValue;
      }
    }
    return target;
  };

  config = require(process.cwd() + '/configs/config.share');

  env = process.env.ENV || 'local';

  file_extra = process.cwd() + '/configs/config.' + env + '.js';

  try {
    config_extra = require(file_extra);
    config = deepMerge(config, config_extra);
  } catch (_error) {
    err = _error;
    console.log(err);
  }

  module.exports = config;

}).call(this);
