// Generated by CoffeeScript 1.9.3
(function() {
  var MysqlClient;

  MysqlClient = (function() {
    function MysqlClient() {}

    MysqlClient.prototype.initialize = function(connection) {
      this.knex = require('knex-mycat')({
        client: 'mysql',
        connection: connection,
        debug: true
      });
      return this.bookshelf = require('bookshelf')(this.knex, {
        debug: true
      });
    };

    return MysqlClient;

  })();

  module.exports = new MysqlClient();

}).call(this);
