// Generated by CoffeeScript 1.9.3
(function() {
  var BusinessError,
      extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
      hasProp = {}.hasOwnProperty;

  BusinessError = (function(superClass) {
    extend(BusinessError, superClass);

    function BusinessError(code, message) {
      Error.captureStackTrace(this, BusinessError);
      if (code) {
        this.code = code;
      }
      if (message) {
        this.message = message;
      }
    }

    return BusinessError;

  })(Error);

  module.exports = BusinessError;

}).call(this);
