// Generated by CoffeeScript 1.9.3
(function() {
  var ParamError;

  ParamError = (function() {
    function ParamError(message) {
      Error.captureStackTrace(this, ParamError);
      if (message) {
        this.message = message;
      }
    }

    return ParamError;

  })();

  module.exports = ParamError;

}).call(this);
