// Generated by CoffeeScript 1.9.3
(function() {
  var UnauthorizedError;

  UnauthorizedError = (function() {
    function UnauthorizedError(message) {
      Error.captureStackTrace(this, UnauthorizedError);
      if (message) {
        this.message = message;
      }
    }

    return UnauthorizedError;

  })();

  module.exports = UnauthorizedError;

}).call(this);
